# @package _global_

env:
  lib: gym
  sublib: mujoco
  name: HalfCheetah-v4
  action_space: continuous
  frame_skip: 1
  truncate_env_steps_at: 1000
  use_truncation_as_termination: True
  time_aware: True
  noop_reset_steps: 0
  noop_is_random: True
  from_pixels: False
  normalize_obs: True
  reward_transforms:
    sign: False
  batchmode: torchrl
  parallel_class: ParallelEnv
  num_envs: 2
  device: cpu
  eval:
    num_envs: 4
    env_steps_per_eval_env: 1000
    video_env_fps: 60

collector:
  total_env_steps: 2_000_000

models:
  share_features: False
  activation: Tanh
  conv_layers:
    num_layers: 0
    num_filters: [ ]  # List of filter sizes.
    kernel_sizes: [ ] # List of kernel sizes.
    strides: [ ]    # List of strides.
  linear_layers:
    num_layers: 2
    layer_size: 64
  actor:
    activation: ${models.activation}
    conv_layers:
      num_layers: ${models.conv_layers.num_layers}
      num_filters: ${models.conv_layers.num_filters}
      kernel_sizes: ${models.conv_layers.kernel_sizes}
      strides: ${models.conv_layers.strides}
    linear_layers:
      num_layers: ${models.linear_layers.num_layers}
      layer_size: ${models.linear_layers.layer_size}
  critic:
    activation: ${models.activation}
    conv_layers:
        num_layers: ${models.conv_layers.num_layers}
        num_filters: ${models.conv_layers.num_filters}
        kernel_sizes: ${models.conv_layers.kernel_sizes}
        strides: ${models.conv_layers.strides}
    linear_layers:
        num_layers: ${models.linear_layers.num_layers}
        layer_size: ${models.linear_layers.layer_size}
